### ISSUE TITLE
Add Server Endpoints for Fetching

### ISSUE THREAD

**Issue by parkr** [parkr/all-your-github-are-belong-to-us#2]
I've stored stuff, now I need to setup a server (or modify the built-in server) to allow me to fetch stuff.

I'm using this guy: https://github.com/jgable/git-at-me/blob/master/lib/Server.js

**Comment by boneskull** [comment]
Curious; why isn't the [statistics API](https://developer.github.com/v3/repos/statistics/) usable for this?
